inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 1
    n_positions: 50

training:
    task: linear_regression
    data: nums
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 2501
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 0
            interval: 2000
        points:
            start: 50
            end: 50
            inc: 0
            interval: 2000

out_dir: ../models/linear_regression

wandb:
    name: "linear_regression_num_bases"
